sudo: required
services:
  -docker

before_install:
  - docker build -t chinrobin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chinrobin/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: elasticbeanstalk-us-east-1-163186350785
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECERT_KEY"